const InitialState = [
  {
    id: "1",
    decrip: "winter",
    img: "assets/img/categori/category_4.png",
    name: "khaddar",
    price: "300",
    discount: "10",
    type: "new",
    category: ["winter"],
  },
  {
    id: "2",
    decrip: "summer",
    img: "assets/img/categori/category_5.png",
    name: "khaddar",
    price: "400",
    discount: "20",
    type: "offer",
    category: ["winter"],
  },
  {
    id: "4",
    decrip: "fresh",
    img: "assets/img/categori/category_6.png",
    name: "khaddar",
    price: "500",
    discount: "20",
    type: "featured",
    category: ["winter"],
  },
  {
    id: "5",
    decrip: "holiday",
    img: "assets/img/categori/category_7.png",
    name: "khaddar",
    price: "200",
    discount: "20",
    type: "new",
    category: ["summer"],
  },
  {
    id: "6",
    decrip: "summer",
    img: "assets/img/categori/category_5.png",
    name: "khaddar",
    price: "600",
    discount: "20",
    type: "offer",
    category: ["winter"],
  },
  {
    id: "7",
    decrip: "fresh",
    img: "assets/img/categori/category_6.png",
    name: "khaddar",
    price: "700",
    discount: "20",
    type: "featured",
    category: ["summer"],
  },
  {
    id: "8",
    decrip: "holiday",
    img: "assets/img/categori/category_7.png",
    name: "khaddar",
    price: "800",
    discount: "20",
    type: "new",
    category: ["summer"],
  },
];
export default InitialState;
